/**
 * The helper an agent's hooks invoke to report a lifecycle event.
 *
 * Ported from `buildAgentCtlScript()` in WebMux
 * `backend/src/adapters/agent-runtime.ts` @ d8c9d5f, rewritten from Python to
 * Node (§23 of the absorption plan): Issue Flow already requires Node ≥ 22.13,
 * and depending on `python3` would add a prerequisite the project does not have
 * today.
 *
 * It is generated as a file rather than shelling out to `issue-flow` itself
 * because it runs on the hot path of every prompt and every tool call. A hook
 * that costs a CLI boot is a hook the user feels.
 */

/** Filename of the generated helper. `.mjs` so Node's module type is never ambiguous. */
export const AGENTCTL_FILENAME = 'issue-flow-agentctl.mjs';

/** Quote a path for a POSIX shell command string, the way the upstream does. */
export function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

/**
 * The generated helper, verbatim.
 *
 * `String.raw` keeps the regex escapes readable, and the script itself contains
 * no template literal, so nothing in it can be mistaken for an interpolation.
 */
export function buildAgentCtlScript(): string {
  return String.raw`#!/usr/bin/env node
// Generated by Issue Flow — do not edit. Rewritten before every invocation.
//
// Reports agent lifecycle events to the control endpoint of the run in flight.
// Reads its credentials from control.env, next to this file, which only exists
// while a run is active.
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const CONTROL_ENV_PATH = join(dirname(fileURLToPath(import.meta.url)), 'control.env');
const REQUEST_TIMEOUT_MS = 2000;
const PR_URL_PATTERN = /https:\/\/github\.com\/[^\s"]+\/pull\/\d+/;
const REQUIRED_KEYS = [
  'ISSUE_FLOW_CONTROL_URL',
  'ISSUE_FLOW_CONTROL_TOKEN',
  'ISSUE_FLOW_RUN_ID',
  'ISSUE_FLOW_PHASE',
];

function readControlEnv() {
  let content;
  try {
    content = readFileSync(CONTROL_ENV_PATH, 'utf-8');
  } catch {
    // No run in flight. Hooks outlive a single invocation, so this is the
    // ordinary state, not a failure.
    return null;
  }
  const env = {};
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    const separator = line.indexOf('=');
    if (line === '' || line.startsWith('#') || separator < 0) continue;
    const key = line.slice(0, separator);
    let value = line.slice(separator + 1);
    if (value.length >= 2 && value.startsWith("'") && value.endsWith("'")) {
      value = value.slice(1, -1).replaceAll("'\\''", "'");
    }
    env[key] = value;
  }
  return env;
}

function parseArgs(argv) {
  const options = {};
  for (let index = 1; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === '--best-effort') continue;
    if (arg === '--lifecycle' || arg === '--url' || arg === '--message') {
      options[arg.slice(2)] = argv[index + 1];
      index += 1;
    }
  }
  return { command: argv[0], options };
}

function buildPayload(kind, options, env) {
  const payload = {
    runId: env.ISSUE_FLOW_RUN_ID,
    phase: env.ISSUE_FLOW_PHASE,
    occurredAt: new Date().toISOString(),
  };
  if (kind === 'agent-stopped') {
    payload.type = 'agent_stopped';
    return payload;
  }
  if (kind === 'status-changed') {
    payload.type = 'agent_status_changed';
    payload.lifecycle = options.lifecycle;
    return payload;
  }
  if (kind === 'pr-opened') {
    payload.type = 'pr_opened';
    if (options.url) payload.url = options.url;
    return payload;
  }
  if (kind === 'runtime-error') {
    payload.type = 'runtime_error';
    payload.message = options.message;
    return payload;
  }
  return null;
}

async function readHookPayload() {
  if (process.stdin.isTTY) return {};
  let raw = '';
  try {
    process.stdin.setEncoding('utf-8');
    for await (const chunk of process.stdin) raw += chunk;
  } catch {
    return {};
  }
  if (raw.trim() === '') return {};
  try {
    const parsed = JSON.parse(raw);
    return parsed !== null && typeof parsed === 'object' && !Array.isArray(parsed) ? parsed : {};
  } catch {
    return {};
  }
}

function* iterStringValues(value) {
  if (typeof value === 'string') {
    yield value;
    return;
  }
  if (Array.isArray(value)) {
    for (const child of value) yield* iterStringValues(child);
    return;
  }
  if (value !== null && typeof value === 'object') {
    for (const child of Object.values(value)) yield* iterStringValues(child);
  }
}

function findPrUrl(value) {
  for (const text of iterStringValues(value)) {
    const match = PR_URL_PATTERN.exec(text);
    if (match !== null) return match[0];
  }
  return null;
}

async function sendPayload(payload, env) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);
  try {
    const response = await fetch(env.ISSUE_FLOW_CONTROL_URL, {
      method: 'POST',
      signal: controller.signal,
      headers: {
        Authorization: 'Bearer ' + env.ISSUE_FLOW_CONTROL_TOKEN,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(payload),
    });
    if (response.status < 200 || response.status >= 300) {
      process.stderr.write('control endpoint returned HTTP ' + response.status + '\n');
      return false;
    }
    return true;
  } catch (error) {
    const detail = error && error.message ? error.message : String(error);
    process.stderr.write('failed to send runtime event: ' + detail + '\n');
    return false;
  } finally {
    clearTimeout(timer);
  }
}

async function maybeSendPrOpened(hookPayload, env) {
  const toolInput = hookPayload.tool_input;
  const isRecord = toolInput !== null && typeof toolInput === 'object' && !Array.isArray(toolInput);
  if (hookPayload.tool_name !== 'Bash' || !isRecord) return;
  const command = toolInput.command;
  if (typeof command !== 'string' || !command.includes('gh pr create')) return;
  const url = findPrUrl(hookPayload.tool_response);
  await sendPayload(buildPayload('pr-opened', url === null ? {} : { url }, env), env);
}

async function main() {
  const env = readControlEnv();
  if (env === null) return;
  if (REQUIRED_KEYS.some((key) => !env[key])) {
    process.stderr.write('issue-flow-agentctl: incomplete control.env, event dropped\n');
    return;
  }

  const { command, options } = parseArgs(process.argv.slice(2));

  if (command === 'codex-session-start' || command === 'codex-permission-request') {
    await sendPayload(buildPayload('status-changed', { lifecycle: 'idle' }, env), env);
    return;
  }
  if (command === 'codex-user-prompt-submit' || command === 'claude-user-prompt-submit') {
    await sendPayload(buildPayload('status-changed', { lifecycle: 'running' }, env), env);
    return;
  }
  if (command === 'codex-post-tool-use' || command === 'claude-post-tool-use') {
    await maybeSendPrOpened(await readHookPayload(), env);
    return;
  }
  if (command === 'codex-stop') {
    await sendPayload(buildPayload('agent-stopped', options, env), env);
    // Codex reads a JSON object back from Stop hooks; an empty one means
    // "nothing to change", which is what reporting an event should imply.
    process.stdout.write('{}');
    return;
  }

  const payload = buildPayload(command, options, env);
  if (payload === null) {
    process.stderr.write('issue-flow-agentctl: unsupported command ' + String(command) + '\n');
    return;
  }
  await sendPayload(payload, env);
}

// Every path exits 0, including a failed POST. This helper reports on an agent
// turn; it may never be the reason one fails. A non-zero UserPromptSubmit hook
// blocks the prompt in Claude Code, which would turn a monitoring hiccup into a
// broken run — the same contract src/web keeps towards the pipeline.
await main();
process.exit(0);
`;
}
