import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import {
  cp,
  mkdir,
  mkdtemp,
  readdir,
  readFile,
  realpath,
  rm,
  symlink,
  writeFile,
} from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test } from 'node:test';
import {
  aggregateResults,
  compareAggregates,
  markdownReport,
  statistics,
} from './skills-benchmark.mjs';
import { artifactRoot, assemble, compare, files, repoRoot, sourceRoot } from './skills-build.mjs';
import { frontmatter, validateSkill } from './skills-check.mjs';
import {
  corpusPath,
  grade,
  materializeScenario,
  observeLine,
  validateCorpus,
} from './skills-eval.mjs';
import {
  gradeGit,
  prepareGitFixture,
  validateFixturePath,
  validateGitAssertion,
  validateGitFixture,
} from './skills-eval-git.mjs';

async function temporary(fn) {
  const root = await mkdtemp(join(tmpdir(), 'issue-flow skill test '));
  try {
    return await fn(root);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
}

function run(file, args = [], options = {}) {
  const result = spawnSync(process.execPath, [file, ...args], {
    encoding: 'utf8',
    timeout: 10000,
    ...options,
  });
  assert.equal(result.error, undefined);
  return result;
}

test('generation is reproducible and tracked artifacts are current', async () => {
  const first = await assemble();
  const second = await assemble();
  assert.deepEqual(first, second);
  assert.deepEqual(await compare(first), []);
});

const manifest = JSON.parse(await readFile(join(sourceRoot, 'manifest.json'), 'utf8'));
test('distributed bundles expose readable code and source provenance', async () => {
  const representativeFunctions = {
    'scripts/artifacts.mjs': 'parseIssueMarkdown',
    'scripts/conventions.mjs': 'branchName',
    'scripts/scaffold.mjs': 'renderAgentsMd',
  };
  for (const [name, resources] of Object.entries(manifest.skills)) {
    for (const [destination, source] of Object.entries(resources)) {
      if (!source.endsWith('.entry.mjs')) continue;
      const code = await readFile(join(artifactRoot, name, destination), 'utf8');
      assert.ok(code.startsWith('// Generated by skills:sync;'), `${name}/${destination}`);
      assert.ok(code.includes(`// Canonical entry point (Issue Flow repository): ${source}\n`));
      assert.ok(code.includes('// Regenerate: cd packages/issue-flow && npm run skills:sync\n'));
      assert.ok(code.includes(`\n// ${source}\n`), 'entry module is identified');
      assert.match(code, /\n\/\/ packages\/issue-flow\/src\/[^\n]+\n/);
      const functionName = representativeFunctions[destination];
      assert.ok(functionName, `Add a readability assertion for ${destination}`);
      assert.match(code, new RegExp(`\nfunction ${functionName}\\([^\\n]*\\) \\{\\n  \\S`));
      assert.match(
        code,
        /\n {2}try \{\n {4}/,
        'entry workflow retains indentation and line breaks',
      );
    }
  }
});

test('eval corpus covers every Skill and rejects escaping fixtures and absent outcomes', async () => {
  const corpus = JSON.parse(await readFile(corpusPath, 'utf8'));
  const names = Object.keys(manifest.skills);
  validateCorpus(corpus, names);
  const escaped = structuredClone(corpus);
  escaped.scenarios[0].fixture = { '../outside': 'invalid' };
  assert.throws(() => validateCorpus(escaped, names));
  const missing = structuredClone(corpus);
  missing.scenarios = missing.scenarios.filter((s) => s.skill !== 'resolve-issue');
  assert.throws(() => validateCorpus(missing, names));
  const missingHoldout = structuredClone(corpus);
  missingHoldout.scenarios = missingHoldout.scenarios.filter(
    (scenario) =>
      !(
        scenario.skill === 'analyze-issue' &&
        scenario.kind === 'positive' &&
        scenario.split === 'holdout'
      ),
  );
  assert.throws(() => validateCorpus(missingHoldout, names));
  const unsafePrompt = structuredClone(corpus);
  const fixture = unsafePrompt.scenarios.find((scenario) => scenario.cliExecute);
  fixture.cliExecute.tasksFile = '../outside';
  assert.throws(() => validateCorpus(unsafePrompt, names));
  const ambiguousPrompt = structuredClone(corpus);
  const ambiguous = ambiguousPrompt.scenarios.find((scenario) => scenario.cliExecute);
  ambiguous.cliReview = ambiguous.cliExecute;
  assert.throws(() => validateCorpus(ambiguousPrompt, names));
  const invalidSplit = structuredClone(corpus);
  invalidSplit.scenarios[0].split = 'secret-test-set';
  assert.throws(() => validateCorpus(invalidSplit, names));
});

test('benchmark aggregates repeated arms without inventing missing usage', () => {
  assert.deepEqual(statistics([10, 20]), {
    reported: 2,
    mean: 15,
    standardDeviation: Math.sqrt(50),
    min: 10,
    max: 20,
  });
  assert.equal(statistics([null, undefined]), null);
  const results = [
    {
      provider: 'claude',
      arm: 'baseline',
      surface: 'skill',
      kind: 'behavior',
      status: 'PASS',
      durationMs: 20,
      usage: { inputTokens: 10, outputTokens: 5 },
      actions: [{ kind: 'tool' }],
    },
    {
      provider: 'claude',
      arm: 'candidate',
      surface: 'skill',
      kind: 'behavior',
      status: 'FAIL',
      durationMs: 10,
      usage: null,
      actions: [],
    },
  ];
  const aggregates = aggregateResults(results);
  assert.equal(aggregates.find((entry) => entry.arm === 'candidate').metrics.totalTokens, null);
  const comparisons = compareAggregates(aggregates);
  assert.equal(comparisons[0].passRate.delta, -1);
  assert.equal(comparisons[0].metrics.durationMs.delta, -10);
  assert.equal(comparisons[0].metrics.totalTokens, null);
  assert.match(
    markdownReport({
      createdAt: '2026-09-06T00:00:00.000Z',
      configuration: { baseline: '1234567' },
      aggregates,
      comparisons,
    }),
    /n\/a/,
  );
});

test('shared eval fixtures materialize inside the scenario and reject invalid references', async () => {
  const scenario = { fixtureFiles: { 'github-pr.mjs': 'github-pr.mjs' } };
  const materialized = await materializeScenario(scenario);
  assert.equal(
    materialized.fixture['github-pr.mjs'],
    await readFile(join(repoRoot, 'evals/skills/fixtures/github-pr.mjs'), 'utf8'),
  );
  assert.equal(scenario.fixture, undefined);
  await assert.rejects(materializeScenario({ fixtureFiles: { '../escape': 'github-pr.mjs' } }));
  await assert.rejects(materializeScenario({ fixtureFiles: { safe: '../scenarios.json' } }));
  await assert.rejects(materializeScenario({ fixtureFiles: { safe: 'missing.mjs' } }));
  await assert.rejects(
    materializeScenario({ ...scenario, fixture: { 'github-pr.mjs': 'duplicate' } }),
  );
});

test('synthetic GitHub retains partially created PRs and the eval rejects claimed metadata', async () =>
  temporary(async (root) => {
    const corpus = JSON.parse(await readFile(corpusPath, 'utf8'));
    const scenario = await materializeScenario(
      corpus.scenarios.find((entry) => entry.id === 'pr-metadata-partial-retry'),
    );
    for (const name of ['github-pr.mjs', 'github-config.json'])
      await writeFile(join(root, name), scenario.fixture[name]);
    const bodyFile = join(root, 'pr-body.md');
    await writeFile(bodyFile, 'A concrete description');
    const invoke = (operation, input) =>
      run(join(root, 'github-pr.mjs'), [operation, JSON.stringify(input ?? {})]);
    const input = {
      title: 'fix: handle null',
      bodyFile,
      base: 'main',
      head: 'feat/request',
      labels: ['bug', 'backend'],
    };
    assert.equal(invoke('create', input).status, 1);
    const partial = JSON.parse(invoke('view').stdout);
    assert.equal(partial.number, 7);
    assert.deepEqual(partial.labels, []);
    const labelRule = scenario.assertions.find((rule) => rule.pattern?.startsWith('^    "labels"'));
    assert.equal(
      (await grade({ kind: 'behavior', assertions: [labelRule] }, 'All labels applied', root, []))
        .length,
      1,
    );
    assert.equal(invoke('edit', { labels: ['bug', 'backend'] }).status, 0);
    assert.deepEqual(JSON.parse(invoke('view').stdout).labels, ['backend', 'bug']);
    assert.deepEqual(await grade({ kind: 'behavior', assertions: [labelRule] }, '', root, []), []);
    assert.equal(invoke('create', input).status, 1);
    const state = JSON.parse(await readFile(join(root, 'github-state.json'), 'utf8'));
    assert.equal(state.creates, 1);
    assert.equal(state.edits, 1);
    assert.equal(state.pr.body, 'A concrete description');
  }));

test('synthetic GitHub adds to manual metadata and rejects unavailable labels', async () =>
  temporary(async (root) => {
    const corpus = JSON.parse(await readFile(corpusPath, 'utf8'));
    const scenario = await materializeScenario(
      corpus.scenarios.find((entry) => entry.id === 'pr-metadata-update-preserves'),
    );
    for (const name of ['github-pr.mjs', 'github-config.json'])
      await writeFile(join(root, name), scenario.fixture[name]);
    const invoke = (operation, input) =>
      run(join(root, 'github-pr.mjs'), [operation, JSON.stringify(input ?? {})]);
    assert.equal(invoke('edit', { labels: ['bug', 'backend'] }).status, 0);
    assert.equal(invoke('edit', { labels: ['invented'] }).status, 1);
    const pr = JSON.parse(invoke('view').stdout);
    assert.deepEqual(pr.labels, ['backend', 'bug', 'manual']);
    assert.deepEqual(pr.assignees, ['alex']);
    assert.deepEqual(pr.reviewers, ['sam']);
    assert.equal(pr.body, 'Maintainer body');
  }));

test('eval grader checks behavior, not just JSON syntax or a claimed pass', async () =>
  temporary(async (root) => {
    assert.ok((await grade({ kind: 'negative', skill: 'review-issue' }, '{}', root, [])).length);
    assert.deepEqual(
      await grade({ kind: 'negative', skill: 'review-issue' }, '{"skill":null}', root, []),
      [],
    );
    assert.ok(
      (
        await grade(
          { kind: 'negative', skill: 'review-issue' },
          '{"skill":"invented-skill"}',
          root,
          [],
        )
      ).length,
    );
    assert.ok(
      (
        await grade(
          { kind: 'behavior', assertions: [{ path: 'missing.json', check: 'completed-evidence' }] },
          'done',
          root,
          [],
        )
      ).length,
    );
    await writeFile(join(root, 'tasks.json'), '{"issueUrl":null}');
    const invalid = await grade(
      { kind: 'behavior', assertions: [{ path: 'tasks.json', check: 'plan' }] },
      'done',
      root,
      [],
    );
    assert.ok(invalid.some((f) => f.includes('canonical validation failed')));
    const changed = await grade(
      {
        kind: 'behavior',
        fixture: { 'tasks.json': 'original' },
        assertions: [{ path: 'tasks.json', unchanged: true }],
      },
      'unchanged',
      root,
      [],
    );
    assert.ok(changed.some((f) => f.includes('changed')));
  }));

test('eval observer retains model/actions and discards thinking and unrelated payloads', () => {
  const evidence = { model: null, actions: [] };
  observeLine(
    JSON.stringify({
      type: 'assistant',
      message: {
        model: 'fixture-model',
        content: [
          { type: 'thinking', thinking: 'must not be retained' },
          { type: 'text', text: 'unneeded intermediate text' },
          {
            type: 'tool_use',
            name: 'Bash',
            input: { command: 'node --test', extra: 'not retained' },
          },
        ],
      },
    }),
    evidence,
  );
  assert.deepEqual(evidence, {
    model: 'fixture-model',
    actions: [{ kind: 'tool', name: 'Bash', detail: 'node --test' }],
  });
});

for (const name of Object.keys(manifest.skills)) {
  test(`${name}: copied directory has complete dependency closure and executable helpers`, async () =>
    temporary(async (root) => {
      const skill = join(root, name);
      await cp(join(artifactRoot, name), skill, { recursive: true });
      assert.deepEqual(await validateSkill(skill), []);
      for (const file of await files(skill)) {
        if (!file.endsWith('.mjs')) continue;
        const result = run(join(skill, file), ['--help'], { cwd: tmpdir() });
        assert.equal(result.status, 0, result.stderr);
        assert.ok(result.stdout.trim());
      }
    }));
}

test('strict YAML rejects duplicate keys, wrong types and aliases', () => {
  assert.throws(() => frontmatter('---\nname: a\nname: b\n---\ntext'));
  assert.throws(() => frontmatter('---\nname: &a a\ndescription: *a\n---\ntext'));
});

test('isolation rejects side-effect package imports and parent paths in instructions', async () =>
  temporary(async (root) => {
    const skill = join(root, 'analyze-issue');
    await cp(join(artifactRoot, 'analyze-issue'), skill, { recursive: true });
    await writeFile(join(skill, 'scripts/leaked.mjs'), "import 'unbundled-package';\n");
    const entry = join(skill, 'SKILL.md');
    await writeFile(entry, `${await readFile(entry, 'utf8')}\nRead \`../../docs/policy.md\`.\n`);
    const errors = await validateSkill(skill);
    assert.ok(errors.some((e) => e.includes('non-bundled dependency')));
    assert.ok(errors.some((e) => e.includes('escaping path')));
  }));

for (const [label, alteration, expected] of [
  [
    'mismatched name',
    (t) => t.replace('name: analyze-issue', 'name: Wrong_Name'),
    /name must match/,
  ],
  ['missing description', (t) => t.replace(/^description:.*\n/m, ''), /Invalid description/],
  [
    'non-string description',
    (t) => t.replace(/^description:.*$/m, 'description: [one, two]'),
    /Invalid description/,
  ],
  [
    'proprietary field',
    (t) => t.replace('license: MIT', 'allowed-tools: Bash'),
    /Unsupported core field/,
  ],
  ['escaping link', (t) => `${t}\n[bad](../outside.md)\n`, /escaping path/],
  ['encoded traversal', (t) => `${t}\n[bad](%2e%2e/outside.md)\n`, /escaping path/],
  ['missing asset', (t) => `${t}\n![missing](assets/missing.svg)\n`, /broken resource/],
  ['missing code reference', (t) => `${t}\nRun \`scripts/missing.mjs\`.\n`, /broken resource/],
  ['broken anchor', (t) => `${t}\n[bad](references/analyze-issue.md#absent)\n`, /missing anchor/],
  [
    'implicit CLI',
    (t) => `${t}\nnpx --yes issue-flow@latest policy --json\n`,
    /implicit CLI installation/,
  ],
]) {
  test(`validator rejects ${label} in an isolated artifact`, async () =>
    temporary(async (root) => {
      const skill = join(root, 'analyze-issue');
      await cp(join(artifactRoot, 'analyze-issue'), skill, { recursive: true });
      const entry = join(skill, 'SKILL.md');
      await writeFile(entry, alteration(await readFile(entry, 'utf8')));
      assert.match((await validateSkill(skill)).join('\n'), expected);
    }));
}

test('escaping resource symlinks fail even when their targets exist', async () =>
  temporary(async (root) => {
    const skill = join(root, 'analyze-issue');
    await cp(join(artifactRoot, 'analyze-issue'), skill, { recursive: true });
    await writeFile(join(root, 'outside.md'), 'private');
    await symlink(join(root, 'outside.md'), join(skill, 'references/outside.md'));
    assert.match((await validateSkill(skill)).join('\n'), /Symlink/);
  }));

test('tampering with either shared or skill-specific output is detected without changing files', async () => {
  const expected = await assemble();
  const path = 'skills/analyze-issue/references/repository-policy.md';
  expected.set(path, Buffer.from('different source'));
  assert.ok((await compare(expected)).includes(path));
  assert.notEqual(await readFile(join(repoRoot, path), 'utf8'), 'different source');
});

test('optional CLI absence, failure, malformed, incompatible and valid payloads', async () =>
  temporary(async (root) => {
    const script = join(artifactRoot, 'analyze-issue/scripts/optional-cli.mjs');
    const env = { ...process.env, PATH: root };
    assert.equal(run(script, ['policy'], { env }).stdout.trim(), 'null');
    const binary = join(root, 'issue-flow');
    for (const [body, expected] of [
      ['exit 1', null],
      ['echo malformed', null],
      ['echo \'{"schemaVersion":99}\'', null],
      [
        'echo \'{"schemaVersion":1,"issues":{},"git":{},"pullRequests":{}}\'',
        { schemaVersion: 1, issues: {}, git: {}, pullRequests: {} },
      ],
    ]) {
      await writeFile(binary, `#!/bin/sh\n${body}\n`, { mode: 0o755 });
      assert.deepEqual(JSON.parse(run(script, ['policy', 'apps/api'], { env }).stdout), expected);
    }
    await writeFile(binary, '#!/bin/sh\nexec /bin/sleep 20\n', { mode: 0o755 });
    const start = Date.now();
    assert.equal(run(script, ['policy'], { env }).stdout.trim(), 'null');
    assert.ok(Date.now() - start < 9000);
  }));

test('packaged issue hash normalizes CRLF and validates metadata without the repository', async () =>
  temporary(async (root) => {
    const script = join(root, 'artifacts.mjs');
    await cp(join(artifactRoot, 'generate-local-issue/scripts/artifacts.mjs'), script);
    const file = join(root, 'issue with spaces.md');
    await writeFile(file, '\r\n# A title\r\n\r\nBody with emoji 🐛\r\n');
    const first = JSON.parse(run(script, ['issue', file], { cwd: root }).stdout);
    await writeFile(file, '# A title\n\nBody with emoji 🐛\n');
    assert.deepEqual(JSON.parse(run(script, ['issue', file], { cwd: root }).stdout), first);
    const metadata = {
      schemaVersion: 1,
      id: '1',
      number: 1,
      source: 'local',
      title: first.title,
      labels: [],
      state: 'open',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      contentHash: first.contentHash,
    };
    const meta = join(root, 'metadata.json');
    await writeFile(meta, JSON.stringify(metadata));
    assert.equal(run(script, ['issue', file, meta]).status, 0);
    await writeFile(meta, JSON.stringify({ ...metadata, contentHash: 'sha256:wrong' }));
    assert.equal(run(script, ['issue', file, meta]).status, 1);
    await writeFile(file, 'Not a title\n# Later heading\n');
    assert.equal(run(script, ['issue', file]).status, 1);
  }));

test('packaged artifact helper shares CLI storage selection and protects workspace artifacts', async () =>
  temporary(async (root) => {
    assert.equal(spawnSync('git', ['init', '-q'], { cwd: root }).status, 0);
    const script = join(artifactRoot, 'analyze-issue/scripts/artifacts.mjs');
    const globalHome = join(root, 'global-state');
    const env = { ...process.env, HOME: root, ISSUE_FLOW_HOME: globalHome, NO_COLOR: '1' };

    const global = run(script, ['resolve', '42', '--json'], { cwd: root, env });
    assert.equal(global.status, 0, global.stderr);
    const globalData = JSON.parse(global.stdout).data;
    assert.equal(globalData.storageMode, 'global');
    assert.ok(globalData.paths.issueDir.startsWith(globalHome));

    await mkdir(join(root, '.issue-flow', 'issues'), { recursive: true });
    const local = run(script, ['prepare', '42', '--json'], { cwd: root, env });
    assert.equal(local.status, 0, local.stderr);
    const localData = JSON.parse(local.stdout).data;
    assert.equal(localData.storageMode, 'workspace');
    assert.equal(
      localData.paths.issueDir,
      join(await realpath(root), '.issue-flow', 'issues', '42'),
    );
    assert.deepEqual(await readdir(localData.paths.issueDir), []);
    const ignore = await readFile(join(root, '.issue-flow', '.gitignore'), 'utf8');
    assert.match(ignore, /^\/issues\/$/m);
    assert.match(ignore, /^\/issue-flow\.db-\*$/m);
    assert.doesNotMatch(ignore, /prompts/);
    await writeFile(join(localData.paths.issueDir, 'tasks.json'), '{}');
    await mkdir(join(root, '.issue-flow', 'prompts'));
    await writeFile(join(root, '.issue-flow', 'prompts', 'plan.md'), 'override');
    assert.equal(
      spawnSync('git', ['check-ignore', '-q', '.issue-flow/issues/42/tasks.json'], { cwd: root })
        .status,
      0,
    );
    assert.equal(
      spawnSync('git', ['check-ignore', '-q', '.issue-flow/prompts/plan.md'], { cwd: root }).status,
      1,
    );
  }));

test('documented plan is accepted by the actual schema; corrupt and duplicate plans fail', async () =>
  temporary(async (root) => {
    const guide = await readFile(
      join(artifactRoot, 'convert-prd-to-json/references/plan-format.md'),
      'utf8',
    );
    const plan = JSON.parse(guide.match(/```json\n([\s\S]*?)\n```/)[1]);
    const file = join(root, 'tasks.json');
    const script = join(artifactRoot, 'convert-prd-to-json/scripts/artifacts.mjs');
    await writeFile(file, JSON.stringify(plan));
    assert.equal(run(script, ['plan', file]).status, 0);
    plan.userStories.push({ ...plan.userStories[0] });
    await writeFile(file, JSON.stringify(plan));
    assert.equal(run(script, ['plan', file]).status, 1);
    plan.lastError = { message: 'wrong shape' };
    await writeFile(file, JSON.stringify(plan));
    assert.equal(run(script, ['plan', file]).status, 1);
  }));

test('standalone execution context retains active criteria without rewriting the plan', async () =>
  temporary(async (root) => {
    const guide = await readFile(
      join(artifactRoot, 'execute-tasks/references/plan-format.md'),
      'utf8',
    );
    const plan = JSON.parse(guide.match(/```json\n([\s\S]*?)\n```/)[1]);
    plan.userStories = [
      {
        ...plan.userStories[0],
        id: 'US-001',
        passes: true,
        notes: 'Old trace',
        description: 'Completed detail',
      },
      {
        ...plan.userStories[0],
        id: 'US-002',
        passes: false,
        dependencies: ['US-001'],
        acceptanceCriteria: ['Preserve current behavior'],
      },
    ];
    const file = join(root, 'tasks.json');
    const original = JSON.stringify(plan);
    await writeFile(file, original);
    const script = join(root, 'artifacts.mjs');
    await cp(join(artifactRoot, 'execute-tasks/scripts/artifacts.mjs'), script);
    const result = run(script, ['plan', file, '--context', '--json'], { cwd: root });
    assert.equal(result.status, 0, result.stderr);
    const context = JSON.parse(result.stdout).data;
    assert.equal(context.activeStory.id, 'US-002');
    assert.deepEqual(context.activeStory.acceptanceCriteria, ['Preserve current behavior']);
    assert.ok(!result.stdout.includes('Completed detail'));
    assert.ok(!result.stdout.includes('Old trace'));
    assert.equal(await readFile(file, 'utf8'), original);
  }));

test('scaffold candidate rendering does not write consumer files', async () =>
  temporary(async (root) => {
    const script = join(artifactRoot, 'init-repository/scripts/scaffold.mjs');
    const rendered = run(script, [], {
      cwd: root,
      input: JSON.stringify({
        projectName: 'A project',
        hasIssueTypes: true,
        documents: ['CONTRIBUTING.md'],
      }),
    });
    assert.equal(rendered.status, 0, rendered.stderr);
    const assets = JSON.parse(rendered.stdout);
    assert.ok(
      assets.some(
        (asset) => asset.path === 'AGENTS.md' && asset.content.includes('CONTRIBUTING.md'),
      ),
    );
    assert.ok(
      !assets.find((asset) => asset.path === '.github/labels.json').content.includes('type:bug'),
    );
    assert.deepEqual(await files(root), []);
  }));

test('isolated helper follows naming precedence and never closes via commit', () => {
  const script = join(artifactRoot, 'create-pr/scripts/conventions.mjs');
  const call = (operation, input) =>
    JSON.parse(run(script, [], { input: JSON.stringify({ operation, input }) }).stdout);
  // Two rungs: a type the project declares (here, through its label map) and
  // `feat`. An Issue Type name is no longer translated into a type.
  assert.equal(call('changeType', { labels: ['bug'] }).type, 'fix');
  assert.equal(call('changeType', { labels: ['enhancement'] }).type, 'feat');
  assert.equal(call('changeType', { labels: [] }).source, 'fallback');
  assert.equal(
    call('branch', { type: 'fix', issueNumber: 42, title: 'Login fails' }),
    'fix/42-login-fails',
  );
  const commit = call('commit', { type: 'fix', subject: 'Fix expiry', issueNumber: 42 });
  assert.match(commit, /Refs #42/);
  assert.doesNotMatch(commit, /Closes/);
  assert.doesNotMatch(commit, /Story:/);
  // `free` hands the message back untouched; the Refs footer is not a format choice.
  assert.equal(
    call('commit', { format: 'free', type: 'fix', subject: 'Fix expiry.', issueNumber: 42 }),
    'Fix expiry.\n\nRefs #42',
  );
  // Only a declared convention replaces the Issue Flow vocabulary.
  assert.equal(call('convention', {}).commit.format, 'conventional');
  assert.equal(call('convention', { declared: true, commitConvention: 'own' }).commit.types, 'any');
});

test('Git fixture setup rejects escaping paths, internal files, commands and invalid refs', () => {
  for (const path of ['../outside', '.git/config', 'sub/.git/hooks/post-checkout'])
    assert.throws(() => validateFixturePath(path));
  assert.throws(() => validateGitFixture({ commands: ['touch /outside'] }));
  assert.throws(() => validateGitFixture({ history: 'not an array' }));
  assert.throws(() => validateGitFixture({ branches: 'main' }));
  assert.throws(() => validateGitFixture({ initialBranch: '--orphan' }));
  assert.throws(() => validateGitFixture({ branches: ['bad name'] }));
  assert.throws(() => validateGitFixture({ dirty: { '../outside': 'bad' } }));
  assert.throws(() => validateGitAssertion({ target: 'git' }));
  assert.throws(() => validateGitAssertion({ target: 'git', commitCount: -1 }));
  assert.throws(() => validateGitAssertion({ target: 'git', commitPattern: '[' }));
});

test('Git assertions reject claimed success and inspect real branch/commit outcomes', async () =>
  temporary(async (root) => {
    const scenario = {
      kind: 'behavior',
      fixture: { 'source.txt': 'original' },
      git: { branches: ['fix/task'], dirty: { 'notes.txt': 'user notes' } },
      assertions: [
        {
          target: 'git',
          branch: 'fix/task',
          branches: ['main', 'fix/task'],
          commitCount: 1,
          commitPattern: '^BUG: repair$',
          unchangedRefs: ['main'],
          commitsOnBranch: 'fix/task',
        },
        { path: 'notes.txt', unchanged: true },
      ],
    };
    const baseline = await prepareGitFixture(root, scenario);
    assert.ok((await grade(scenario, 'Done; committed on fix/task', root, [], baseline)).length);
    const git = (args) => execFileSync('git', args, { cwd: root, encoding: 'utf8' });
    git(['switch', '-q', 'fix/task']);
    await writeFile(join(root, 'source.txt'), 'repaired');
    git(['add', 'source.txt']);
    git(['commit', '-qm', 'BUG: repair']);
    assert.deepEqual(await grade(scenario, 'done', root, [], baseline), []);
    assert.ok(gradeGit(root, { commitPattern: '^fix:' }, baseline).length);
    git(['switch', '-q', 'main']);
    git(['commit', '-q', '--allow-empty', '-m', 'BUG: misplaced']);
    const failures = await grade(scenario, 'still correct', root, [], baseline);
    assert.ok(failures.some((f) => f.includes('ref changed: main')));
    assert.ok(failures.some((f) => f.includes('outside fix/task')));
    await writeFile(join(root, 'notes.txt'), 'overwritten');
    assert.ok(
      (await grade(scenario, 'preserved', root, [], baseline)).some(
        (f) => f === 'notes.txt: changed',
      ),
    );
  }));

test('Git fixtures preserve detached HEAD and exclude existing history from new commits', async () =>
  temporary(async (root) => {
    const baseline = await prepareGitFixture(root, {
      fixture: { 'file.txt': 'baseline' },
      git: {
        initialBranch: 'develop',
        history: ['BUG: previous', 'DOC: previous'],
        detached: true,
      },
    });
    assert.equal(baseline.branch, '');
    assert.deepEqual(
      gradeGit(
        root,
        { branch: '', branches: ['develop'], commitCount: 0, unchangedRefs: ['develop'] },
        baseline,
      ),
      [],
    );
    assert.ok(gradeGit(root, { branch: 'develop' }, baseline).length);
    assert.ok(gradeGit(root, { commitPattern: 'BUG' }, baseline).length);
    assert.deepEqual(gradeGit(root, { commitCount: 0 }, null), ['Git baseline missing']);
  }));
